services:
  postgres:
    image: postgres:15.4-alpine
    ports:
      - "127.0.0.1:5432:5432"
    container_name: pg
    volumes:
      - type: volume
        source: data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./config/initdb
        target: /docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fileverse
      TZ: UTC
    restart: unless-stopped

  ipfs:
    image: ipfs/kubo
    container_name: ipfs-node
    ports:
      - "4001:4001" # IPFS swarm
      - "5001:5001" # API and Web UI
      - "8080:8080" # Gateway
    volumes:
      - type: volume
        source: ipfs_staging
        target: /export
      - type: volume
        source: ipfs_data
        target: /data/ipfs
    restart: unless-stopped

volumes:
  data:
  ipfs_staging:
  ipfs_data:

networks:
  default:
    driver: bridge
